import { useState, useEffect, useRef } from "react";
import { useMentor } from "@/lib/mentor-context";
import { invokeFunction } from "@/lib/ai-stream";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Slider } from "@/components/ui/slider";
import { Loader2, RefreshCw, Map, ExternalLink, HelpCircle } from "lucide-react";
import { toast } from "sonner";
import { motion } from "framer-motion";

const KNOWN_SITES: Record<string, string> = {
  "mdn": "https://developer.mozilla.org",
  "mdn web docs": "https://developer.mozilla.org",
  "freecodecamp": "https://www.freecodecamp.org",
  "free code camp": "https://www.freecodecamp.org",
  "w3schools": "https://www.w3schools.com",
  "coursera": "https://www.coursera.org",
  "udemy": "https://www.udemy.com",
  "khan academy": "https://www.khanacademy.org",
  "codecademy": "https://www.codecademy.com",
  "leetcode": "https://leetcode.com",
  "hackerrank": "https://www.hackerrank.com",
  "github": "https://github.com",
  "stack overflow": "https://stackoverflow.com",
  "stackoverflow": "https://stackoverflow.com",
  "kaggle": "https://www.kaggle.com",
  "pluralsight": "https://www.pluralsight.com",
  "edx": "https://www.edx.org",
  "youtube": "https://www.youtube.com",
  "css tricks": "https://css-tricks.com",
  "css-tricks": "https://css-tricks.com",
  "smashing magazine": "https://www.smashingmagazine.com",
  "digital ocean": "https://www.digitalocean.com/community/tutorials",
  "digitalocean": "https://www.digitalocean.com/community/tutorials",
  "geeksforgeeks": "https://www.geeksforgeeks.org",
  "tensorflow": "https://www.tensorflow.org",
  "pytorch": "https://pytorch.org",
  "scikit-learn": "https://scikit-learn.org",
  "react": "https://react.dev",
  "vue": "https://vuejs.org",
  "angular": "https://angular.dev",
  "node.js": "https://nodejs.org",
  "python": "https://docs.python.org",
  "rust": "https://doc.rust-lang.org/book/",
  "owasp": "https://owasp.org",
};

function parseResource(resource: string) {
  // Try "Name | URL" format
  const pipeMatch = resource.match(/^(.+?)\s*\|\s*(https?:\/\/.+)$/);
  if (pipeMatch) return { label: pipeMatch[1].trim(), url: pipeMatch[2].trim() };

  // Try to find a URL anywhere in the string
  const urlMatch = resource.match(/(https?:\/\/[^\s]+)/);
  if (urlMatch) {
    const url = urlMatch[1];
    const label = resource.replace(url, "").replace(/[-–—|:]\s*$/, "").trim() || url;
    return { label, url };
  }

  // Match against known sites
  const lower = resource.toLowerCase();
  for (const [key, url] of Object.entries(KNOWN_SITES)) {
    if (lower.includes(key)) {
      return { label: resource, url };
    }
  }

  // Fallback: Google search link
  return { label: resource, url: `https://www.google.com/search?q=${encodeURIComponent(resource)}` };
}

export default function RoadmapTab() {
  const { interest, level, roadmap, setRoadmap, toggleMilestone, setMilestoneProgress } = useMentor();
  const [loading, setLoading] = useState(false);
  const autoGenerated = useRef<Set<string>>(new Set());

  const generate = async () => {
    setLoading(true);
    try {
      const data = await invokeFunction<{ roadmap: typeof roadmap }>("roadmap", { interest, level });
      setRoadmap(data.roadmap.map((m) => ({ ...m, completed: false, progress: 0 })));
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : "Failed to generate roadmap");
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate on first visit per domain+level
  const key = `${interest}-${level}`;
  useEffect(() => {
    if (roadmap.length === 0 && !autoGenerated.current.has(key)) {
      autoGenerated.current.add(key);
      generate();
    }
  }, [key]); // eslint-disable-line react-hooks/exhaustive-deps
  if (roadmap.length === 0) {
    return (
      <motion.div className="text-center py-20" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.3 }}>
        <motion.div
          animate={{ y: [0, -8, 0] }}
          transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
        >
          <Map className="h-14 w-14 text-primary mx-auto mb-4" />
        </motion.div>
        <h2 className="text-2xl font-bold gradient-text mb-2">Generate Your Learning Roadmap</h2>
        <p className="text-muted-foreground mb-6">Get a personalized step-by-step path for <span className="text-primary font-medium">{interest}</span> at <span className="text-primary font-medium">{level}</span> level.</p>
        <motion.div whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}>
          <Button onClick={generate} disabled={loading} className="gradient-primary text-primary-foreground px-8">
            {loading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
            Generate Roadmap
          </Button>
        </motion.div>
      </motion.div>
    );
  }

  const completed = roadmap.filter((m) => m.completed).length;
  const progress = roadmap.length > 0
    ? Math.round(roadmap.reduce((s, m) => s + (m.progress ?? 0), 0) / roadmap.length)
    : 0;

  return (
    <div className="space-y-4">
      <motion.div
        className="flex items-center justify-between p-3 rounded-lg bg-card/60 border border-border/50"
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="flex items-center gap-3">
          <p className="text-sm text-muted-foreground">{completed}/{roadmap.length} done · {progress}% overall</p>
          <div className="w-24 h-2 bg-muted rounded-full overflow-hidden">
            <motion.div
              className="h-full gradient-primary rounded-full"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.5 }}
            />
          </div>
        </div>
        <Button variant="outline" size="sm" onClick={generate} disabled={loading}>
          <RefreshCw className={`h-4 w-4 mr-1 ${loading ? "animate-spin" : ""}`} />
          Regenerate
        </Button>
      </motion.div>
      {roadmap.map((milestone, i) => (
        <motion.div
          key={i}
          initial={{ opacity: 0, x: -16 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: i * 0.06, duration: 0.3 }}
          whileHover={{ x: 4 }}
        >
          <Card className={`transition-all duration-300 border-border/50 ${milestone.completed ? "opacity-60 bg-muted/30" : "hover:shadow-md hover:border-primary/20"}`}>
            <CardHeader className="pb-2 flex flex-row items-start gap-3">
              <Checkbox checked={milestone.completed} onCheckedChange={() => toggleMilestone(i)} className="mt-1" />
              <div>
                <CardTitle className={`text-base ${milestone.completed ? "line-through" : ""}`}>
                  <span className="text-primary font-bold mr-1">{i + 1}.</span> {milestone.title}
                </CardTitle>
                <p className="text-sm text-muted-foreground mt-1">{milestone.description}</p>
              </div>
            </CardHeader>
            <CardContent className="pt-0 pl-12 space-y-3">
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-xs font-medium text-primary/70">Progress</span>
                  <span className="text-xs font-semibold text-primary">{milestone.progress ?? 0}%</span>
                </div>
                <Slider
                  value={[milestone.progress ?? 0]}
                  onValueChange={(v) => setMilestoneProgress(i, v[0])}
                  max={100}
                  step={5}
                />
              </div>
            </CardContent>
            {milestone.resources.length > 0 && (
              <CardContent className="pt-0 pl-12">
                <p className="text-xs font-medium text-primary/70 mb-1">Resources:</p>
                <ul className="text-sm space-y-1.5">
                  {milestone.resources.map((r, j) => {
                    const { label, url } = parseResource(r);
                    return (
                      <li key={j}>
                        {url ? (
                          <a
                            href={url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1.5 text-primary hover:text-primary/80 hover:underline transition-colors"
                          >
                            <ExternalLink className="h-3 w-3 shrink-0" />
                            {label}
                          </a>
                        ) : (
                          <span className="text-muted-foreground">• {label}</span>
                        )}
                      </li>
                    );
                  })}
                </ul>
              </CardContent>
            )}
          </Card>
        </motion.div>
      ))}
    </div>
  );
}
