import { useState, useEffect, useRef } from "react";
import { useMentor } from "@/lib/mentor-context";
import { invokeFunction } from "@/lib/ai-stream";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Slider } from "@/components/ui/slider";
import { Loader2, RefreshCw, Map, ExternalLink, HelpCircle, History } from "lucide-react";
import { toast } from "sonner";
import { motion, useReducedMotion, type Variants } from "framer-motion";

const containerVariants: Variants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.15,
    },
  },
};

const itemVariants: Variants = {
  hidden: { opacity: 0, y: 28, scale: 0.97 },
  show: {
    opacity: 1,
    y: 0,
    scale: 1,
    transition: {
      type: "spring",
      stiffness: 120,
      damping: 18,
      mass: 0.8,
    },
  },
};

const innerVariants: Variants = {
  hidden: { opacity: 0, x: -12 },
  show: {
    opacity: 1,
    x: 0,
    transition: { type: "spring", stiffness: 180, damping: 22 },
  },
};

const lineDrawVariants: Variants = {
  hidden: { scaleY: 0, originY: 0 },
  show: {
    scaleY: 1,
    transition: { duration: 0.6, ease: "easeInOut", delay: 0.1 },
  },
};


const KNOWN_SITES: Record<string, string> = {
  "mdn": "https://developer.mozilla.org",
  "mdn web docs": "https://developer.mozilla.org",
  "freecodecamp": "https://www.freecodecamp.org",
  "free code camp": "https://www.freecodecamp.org",
  "w3schools": "https://www.w3schools.com",
  "coursera": "https://www.coursera.org",
  "udemy": "https://www.udemy.com",
  "khan academy": "https://www.khanacademy.org",
  "codecademy": "https://www.codecademy.com",
  "leetcode": "https://leetcode.com",
  "hackerrank": "https://www.hackerrank.com",
  "github": "https://github.com",
  "stack overflow": "https://stackoverflow.com",
  "stackoverflow": "https://stackoverflow.com",
  "kaggle": "https://www.kaggle.com",
  "pluralsight": "https://www.pluralsight.com",
  "edx": "https://www.edx.org",
  "youtube": "https://www.youtube.com",
  "css tricks": "https://css-tricks.com",
  "css-tricks": "https://css-tricks.com",
  "smashing magazine": "https://www.smashingmagazine.com",
  "digital ocean": "https://www.digitalocean.com/community/tutorials",
  "digitalocean": "https://www.digitalocean.com/community/tutorials",
  "geeksforgeeks": "https://www.geeksforgeeks.org",
  "tensorflow": "https://www.tensorflow.org",
  "pytorch": "https://pytorch.org",
  "scikit-learn": "https://scikit-learn.org",
  "react": "https://react.dev",
  "vue": "https://vuejs.org",
  "angular": "https://angular.dev",
  "node.js": "https://nodejs.org",
  "python": "https://docs.python.org",
  "rust": "https://doc.rust-lang.org/book/",
  "owasp": "https://owasp.org",
};

function parseResource(resource: string) {
  // Try "Name | URL" format
  const pipeMatch = resource.match(/^(.+?)\s*\|\s*(https?:\/\/.+)$/);
  if (pipeMatch) return { label: pipeMatch[1].trim(), url: pipeMatch[2].trim() };

  // Try to find a URL anywhere in the string
  const urlMatch = resource.match(/(https?:\/\/[^\s]+)/);
  if (urlMatch) {
    const url = urlMatch[1];
    const label = resource.replace(url, "").replace(/[-–—|:]\s*$/, "").trim() || url;
    return { label, url };
  }

  // Match against known sites
  const lower = resource.toLowerCase();
  for (const [key, url] of Object.entries(KNOWN_SITES)) {
    if (lower.includes(key)) {
      return { label: resource, url };
    }
  }

  // Fallback: Google search link
  return { label: resource, url: `https://www.google.com/search?q=${encodeURIComponent(resource)}` };
}

export default function RoadmapTab() {
  const { interest, level, roadmap, setRoadmap, toggleMilestone, setMilestoneProgress, requestMilestoneQuiz, quizResults } = useMentor();
  const [loading, setLoading] = useState(false);
  const autoGenerated = useRef<Set<string>>(new Set());

  const generate = async () => {
    setLoading(true);
    try {
      const data = await invokeFunction<{ roadmap: typeof roadmap }>("roadmap", { interest, level });
      setRoadmap(data.roadmap.map((m) => ({ ...m, completed: false, progress: 0 })));
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : "Failed to generate roadmap");
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate on first visit per domain+level
  const key = `${interest}-${level}`;
  useEffect(() => {
    if (roadmap.length === 0 && !autoGenerated.current.has(key)) {
      autoGenerated.current.add(key);
      generate();
    }
  }, [key]); // eslint-disable-line react-hooks/exhaustive-deps
  if (roadmap.length === 0) {
    return (
      <motion.div className="text-center py-20" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.3 }}>
        <motion.div
          animate={{ y: [0, -8, 0] }}
          transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
        >
          <Map className="h-14 w-14 text-primary mx-auto mb-4" />
        </motion.div>
        <h2 className="text-2xl font-bold gradient-text mb-2">Generate Your Learning Roadmap</h2>
        <p className="text-muted-foreground mb-6">Get a personalized step-by-step path for <span className="text-primary font-medium">{interest}</span> at <span className="text-primary font-medium">{level}</span> level.</p>
        <motion.div whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}>
          <Button onClick={generate} disabled={loading} className="gradient-primary text-primary-foreground px-8">
            {loading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
            Generate Roadmap
          </Button>
        </motion.div>
      </motion.div>
    );
  }

  const completed = roadmap.filter((m) => m.completed).length;
  const progress = roadmap.length > 0
    ? Math.round(roadmap.reduce((s, m) => s + (m.progress ?? 0), 0) / roadmap.length)
    : 0;

  return (
    <motion.div
      className="space-y-4 relative"
      variants={containerVariants}
      initial="hidden"
      animate="show"
    >
      <motion.div
        className="flex items-center justify-between p-3 rounded-lg bg-card/60 border border-border/50"
        variants={itemVariants}
      >
        <div className="flex items-center gap-3">
          <p className="text-sm text-muted-foreground">{completed}/{roadmap.length} done · {progress}% overall</p>
          <div className="w-24 h-2 bg-muted rounded-full overflow-hidden">
            <motion.div
              className="h-full gradient-primary rounded-full"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.8, ease: "easeOut", delay: 0.3 }}
            />
          </div>
        </div>
        <Button variant="outline" size="sm" onClick={generate} disabled={loading}>
          <RefreshCw className={`h-4 w-4 mr-1 ${loading ? "animate-spin" : ""}`} />
          Regenerate
        </Button>
      </motion.div>

      {/* Connecting timeline line */}
      <motion.div
        className="absolute left-[19px] top-[68px] bottom-4 w-0.5 bg-gradient-to-b from-primary/40 via-primary/20 to-transparent rounded-full"
        variants={lineDrawVariants}
        initial="hidden"
        animate="show"
      />

      {roadmap.map((milestone, i) => (
        <motion.div
          key={i}
          variants={itemVariants}
          whileHover={{ x: 6, transition: { type: "spring", stiffness: 250, damping: 20 } }}
          className="relative"
        >
          {/* Step number badge */}
          <motion.div
            className="absolute -left-1 top-4 z-10 flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground text-xs font-bold shadow-lg shadow-primary/30 ring-2 ring-background"
            initial={{ scale: 0, rotate: -45 }}
            animate={{ scale: 1, rotate: 0 }}
            transition={{ type: "spring", stiffness: 300, damping: 15, delay: 0.15 + i * 0.1 }}
          >
            {i + 1}
          </motion.div>

          <Card className={`ml-10 transition-all duration-300 border-border/50 ${milestone.completed ? "opacity-60 bg-muted/30" : "hover:shadow-md hover:border-primary/20"}`}>
            <CardHeader className="pb-2 flex flex-row items-start gap-3 pl-4">
              <Checkbox checked={milestone.completed} onCheckedChange={() => toggleMilestone(i)} className="mt-1" />
              <div>
                <CardTitle className={`text-base ${milestone.completed ? "line-through" : ""}`}>
                  {milestone.title}
                </CardTitle>
                <motion.p
                  className="text-sm text-muted-foreground mt-1"
                  variants={innerVariants}
                  initial="hidden"
                  whileInView="show"
                  viewport={{ once: true }}
                >
                  {milestone.description}
                </motion.p>
              </div>
            </CardHeader>
            <CardContent className="pt-0 pl-12 space-y-3">
              <motion.div
                variants={innerVariants}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true }}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-xs font-medium text-primary/70">Progress</span>
                  <motion.span
                    className="text-xs font-semibold text-primary"
                    key={milestone.progress}
                    initial={{ scale: 1.4, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    transition={{ type: "spring", stiffness: 300, damping: 20 }}
                  >
                    {milestone.progress ?? 0}%
                  </motion.span>
                </div>
                <Slider
                  value={[milestone.progress ?? 0]}
                  onValueChange={(v) => setMilestoneProgress(i, v[0])}
                  max={100}
                  step={5}
                />
              </motion.div>

              <motion.div
                variants={innerVariants}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true }}
              >
                <Button
                  size="sm"
                  variant="outline"
                  className="gap-1.5 border-primary/30 text-primary hover:bg-primary/10"
                  onClick={() => requestMilestoneQuiz({ index: i, title: milestone.title, description: milestone.description })}
                >
                  <HelpCircle className="h-3.5 w-3.5" />
                  Take Module Quiz
                </Button>
              </motion.div>

              {(() => {
                const titleLower = milestone.title.toLowerCase().trim();
                const history = quizResults
                  .filter((r) => {
                    const t = r.topic?.toLowerCase().trim() ?? "";
                    return t === titleLower || t.includes(titleLower) || titleLower.includes(t);
                  })
                  .sort((a, b) => b.timestamp - a.timestamp);
                if (history.length === 0) return null;
                return (
                  <motion.div
                    className="rounded-md border border-border/50 bg-muted/20 p-3"
                    variants={innerVariants}
                    initial="hidden"
                    whileInView="show"
                    viewport={{ once: true }}
                  >
                    <div className="flex items-center gap-1.5 mb-2">
                      <History className="h-3.5 w-3.5 text-primary/70" />
                      <span className="text-xs font-medium text-primary/70">
                        Quiz History ({history.length})
                      </span>
                    </div>
                    <ul className="space-y-1.5">
                      {history.map((r, idx) => {
                        const pct = Math.round((r.score / r.total) * 100);
                        const date = new Date(r.timestamp).toLocaleDateString(undefined, {
                          month: "short", day: "numeric", year: "numeric",
                        });
                        const color = pct >= 80 ? "text-success" : pct >= 50 ? "text-warning" : "text-destructive";
                        return (
                          <li key={idx} className="flex items-center justify-between text-xs">
                            <span className="text-muted-foreground">{date}</span>
                            <span className="text-muted-foreground truncate max-w-[40%]" title={r.topic}>
                              {r.topic}
                            </span>
                            <span className={`font-semibold ${color}`}>
                              {r.score}/{r.total} · {pct}%
                            </span>
                          </li>
                        );
                      })}
                    </ul>
                  </motion.div>
                );
              })()}
            </CardContent>
            {milestone.resources.length > 0 && (
              <CardContent className="pt-0 pl-12">
                <motion.p
                  className="text-xs font-medium text-primary/70 mb-1"
                  variants={innerVariants}
                  initial="hidden"
                  whileInView="show"
                  viewport={{ once: true }}
                >
                  Resources:
                </motion.p>
                <motion.ul
                  className="text-sm space-y-1.5"
                  variants={containerVariants}
                  initial="hidden"
                  whileInView="show"
                  viewport={{ once: true }}
                >
                  {milestone.resources.map((r, j) => {
                    const { label, url } = parseResource(r);
                    return (
                      <motion.li
                        key={j}
                        variants={innerVariants}
                        whileHover={{ x: 4, transition: { type: "spring", stiffness: 300, damping: 20 } }}
                      >
                        {url ? (
                          <a
                            href={url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1.5 text-primary hover:text-primary/80 hover:underline transition-colors"
                          >
                            <ExternalLink className="h-3 w-3 shrink-0" />
                            {label}
                          </a>
                        ) : (
                          <span className="text-muted-foreground">• {label}</span>
                        )}
                      </motion.li>
                    );
                  })}
                </motion.ul>
              </CardContent>
            )}
          </Card>
        </motion.div>
      ))}
    </motion.div>
  );
}
